Repository OpenAF/openaf, pull requests merged in 2021-12, with the labels that each got.

#312 if an opack is local than add it quickly to the opack local db (usefull in ojobs)
  js/openaf.js
Labels: enhancement

#313 Update README.md
  README.md
Labels: enhancement, documentation

#314 ow.ch.elasticsearch: stamp option
  js/owrap.ch.js
Labels: enhancement

#315 $atomic: +set,+setIf
  js/openaf.js
Labels: enhancement

#316 opromise improvements
  js/openaf.js
  js/owrap.ch.js
  tests/autoTestAll.Generic.js
  tests/autoTestAll.Server.js
Labels: bug, enhancement

#318 oJob check
  js/openafsigil.js
  js/owrap.oJob.js
  tests/autoTestAll.Generic.js
Labels: enhancement
