Repository OpenAF/openaf, pull requests merged in 2023-12, with the labels that each got.

#854 Add sysuptime to trap method to allow opennms integration
  src/openaf/plugins/SNMP.java
Labels: enhancement

#856 T8
  js/openafconsole.js
  js/owrap.java.js
  lib/jna-5.13.0.jar
  lib/jna-5.14.0.jar
  lib/jna-platform-5.13.0.jar
  lib/jna-platform-5.14.0.jar
  lib/kotlin-stdlib-1.9.20.jar
  lib/okio-3.6.0.jar
  lib/okio-3.7.0.jar
  lib/okio-jvm-3.6.0.jar
  lib/okio-jvm-3.7.0.jar
  pom.xml
  tests/autoTestAll.HTTP.js
  versionsAndDeps.json
Labels: enhancement

#874 t8
  pom.xml
Labels: dependencies

#886 Add test case for AwaitAll functionality
  tests/autoTestAll.Generic.js
  tests/autoTestAll.Generic.yaml
Labels: enhancement

#888 Fix formatting issue in askChoose function
  js/openaf.js
Labels: bug

#892 bump commons-email
  lib/commons-email-1.5.jar
  lib/commons-email-1.6.0.jar
  pom.xml
  versionsAndDeps.json
Labels: enhancement
